apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  namespace: {{ template "service-namespace" . }}
  name: al-service-priority
value: 0
preemptionPolicy: Never
globalDefault: false
description: "AL analysis services should be low priority and non-preempting."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  namespace: {{ .Release.Name }}
  name: al-core-priority
value: 10000
globalDefault: false
description: "AL core services have medium priority and preempt other services when needed."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  namespace: {{ .Release.Name }}
  name: al-infra
value: 100000
globalDefault: false
description: "High priority class for infrastructure containers"