apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-scaling-manager
  labels:
    app: assemblyline
  annotations:
    {{- range $key, $value := .Values.serviceAccountAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
---
# This role combines all permissions needed for the scaling-manager SA at the cluster level (used by updater and scaler components)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-scaling-manager-cluster-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["watch"]
{{ if .Values.configuration.core.scaler.cluster_pod_list }}
- apiGroups: [""]
  resources: ["pods",]
  verbs: ["watch"]
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-scaling-manager-cluster-role
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-scaling-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-scaling-manager-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
# This role combines all permissions needed for the scaling-manager SA at the namespace level (used by updater and scaler components)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-scaling-manager-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "patch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["create", "delete", "list", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "delete", "get", "watch"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch", "update", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-scaling-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-scaling-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-scaling-manager-role
  apiGroup: rbac.authorization.k8s.io
---
