apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater
  labels:
    app: assemblyline
    section: core
    component: updater
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionCount }}
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: updater
  template:
    metadata:
      labels:
        app: assemblyline
        section: core
        component: updater
    spec:
      serviceAccountName: {{ .Release.Name }}-scaling-manager
      priorityClassName: al-core-priority
      containers:
        - name: updater
          image: {{ .Values.assemblylineCoreImage }}:{{ .Values.release }}
          imagePullPolicy: Always
          {{ if .Values.enableCoreDebugging}}
          command: ['python', '-m', 'debugpy', '--listen', 'localhost:5678', '-m', 'assemblyline_core.updater.run_updater']
          {{ else }}
          command: ['python', '-m', 'assemblyline_core.updater.run_updater']
          {{ end}}
          volumeMounts:
          {{ include "assemblyline.coreMounts" . | indent 12 }}
          env:
          {{ include "assemblyline.coreEnv" . | indent 12 }}
            - name: KUBERNETES_AL_CONFIG
              value: {{ .Release.Name }}-global-config
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: UI_SERVER
              value: http://internal-ui:5000
            - name: SERVICE_API_HOST
              value: http://service-server:5003
          livenessProbe:
            exec:
              command: [ "bash", "-c", "if [[ ! `find /tmp/heartbeat -newermt '-30 seconds'` ]]; then false; fi" ]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: "0.5"
              {{ if .Values.namespaceResourceLimited }}
              memory: "1Gi"
              {{ end }}
            requests:
              cpu: {{ .Values.updaterReqCPU }}
      volumes:
      {{ include "assemblyline.coreVolumes" . | indent 8 }}
