apiVersion: apps/v1
kind: Deployment
metadata:
  name: updater
  labels:
    app: assemblyline
    section: core
    component: updater
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionCount }}
  selector:
    matchLabels:
      app: assemblyline
      section: core
      component: updater
  template:
    metadata:
      annotations:
        checksum/config: {{ .Values.configuration | toYaml | sha256sum }}
      labels:
        app: assemblyline
        section: core
        component: updater
        {{ include "assemblyline.coreLabels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Release.Name }}-scaling-manager
      priorityClassName: al-core-priority
      affinity:
        nodeAffinity:
          {{ include "assemblyline.nodeAffinity" . | indent 10 }}
      tolerations:
        {{ include "assemblyline.tolerations" . | indent 8 }}
      containers:
        - name: updater
          image: {{ .Values.assemblylineCoreImage }}:{{ .Values.release }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{ if .Values.enableCoreDebugging}}
          command: ['python', '-m', 'debugpy', '--listen', 'localhost:5678', '-m', 'assemblyline_core.updater.run_updater']
          {{ else }}
          command: ['python', '-m', 'assemblyline_core.updater.run_updater']
          {{ end}}
          securityContext:
            {{ include "assemblyline.coreSecurityContext" . | indent 12 }}          
          volumeMounts:
          {{ include "assemblyline.coreMounts" . | indent 12 }}
          env:
          {{ include "assemblyline.coreEnv" . | indent 12 }}
            - name: KUBERNETES_AL_CONFIG
              value: {{ .Release.Name }}-global-config
            - name: RELEASE_NAME
              value: {{ .Release.Name }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_API_HOST
              value: {{ if .Values.enableInternalEncryption }}https{{ else }}http{{ end }}://service-server:5003
            - name: PRIVILEGED_SERVICE_ACCOUNT_NAME
              value: {{ .Values.privilegedServiceAccountName }}
          livenessProbe:
            exec:
              command: [ "bash", "-c", "if [[ ! `find /tmp/heartbeat -newermt '-30 seconds'` ]]; then false; fi" ]
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            limits:
              cpu: {{ .Values.updaterLimCPU }}
              memory: {{ .Values.updaterLimRam }}
            requests:
              cpu: {{ .Values.updaterReqCPU }}
              memory: {{ .Values.updaterReqRam }}
      volumes:
      {{ include "assemblyline.coreVolumes" . | indent 8 }}
