# If you change the elasticsearch version, remember to also change the version at:
#   - values.yaml: the init container image tag
#   - logstash-deployment.yaml: It isn't launched via chart due to compatibility issues
dependencies:
  - name: elasticsearch
    repository: https://helm.elastic.co/
    version: 8.5.1
    alias: datastore
    condition: internalDatastore
  - name: filebeat
    repository: https://helm.elastic.co/
    version: 7.17.3
    alias: filebeat
    condition: enableLogging
  - name: metricbeat
    repository: https://helm.elastic.co/
    version: 7.17.3
    alias: metricbeat
    condition: enableMetricbeat
  - name: elasticsearch
    repository: https://helm.elastic.co/
    version: 8.5.1
    alias: log-storage
    condition: seperateInternalELKStack
  - name: kibana
    repository: https://helm.elastic.co/
    version: 7.17.3
    alias: kibana
    condition: internalELKStack
  - name: minio
    repository: https://helm.min.io/
    version: 5.0
    alias: filestore
    condition: internalFilestore
